import type { Metadata } from "next";
import "./globals.css";
import { PoppinsFont } from "@/app/lib/font";
import { AuthProvider } from "./lib/context/AuthContext";

export const metadata: Metadata = {
  title: "Stock Flow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <link rel="shortcut icon" href="/icon/Icone.svg" type="image/svg" />
      </head>
      <body className={PoppinsFont.className}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
